In [5]:
import numpy

world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter="," ,dtype=str)
print(type(world_alcohol))

OSError: world_alcohol.txt not found.

In [4]:
#The numpy.array() function can take a list or list of lists as input. When we input a list, we get a one-dimensional array as a result:
vector = numpy.array([5, 10, 15, 20])
#When we input a list of lists, we get a matrix as a result:
matrix = numpy.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print vector
print matrix

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(vector)? (<ipython-input-4-08d26e629563>, line 5)

In [1]:
#We can use the ndarray.shape property to figure out how many elements are in the array
vector = numpy.array([1, 2, 3, 4])
print(vector.shape)
#For matrices, the shape property contains a tuple with 2 elements.
matrix = numpy.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)

NameError: name 'numpy' is not defined

In [5]:
#Each value in a NumPy array has to have the same data type
#NumPy will automatically figure out an appropriate data type when reading in data or converting lists to arrays. 
#You can check the data type of a NumPy array using the dtype property.
numbers = numpy.array([1, 2, 3, 4])
numbers.dtype

dtype('int32')

In [10]:
#When NumPy can't convert a value to a numeric data type like float or integer, it uses a special nan value that stands for Not a Number
#nan is the missing data
#1.98600000e+03 is actually 1.986 * 10 ^ 3
world_alcohol

array([[             nan,              nan,              nan,
                     nan,              nan],
       [  1.98600000e+03,              nan,              nan,
                     nan,   0.00000000e+00],
       [  1.98600000e+03,              nan,              nan,
                     nan,   5.00000000e-01],
       ..., 
       [  1.98700000e+03,              nan,              nan,
                     nan,   7.50000000e-01],
       [  1.98900000e+03,              nan,              nan,
                     nan,   1.50000000e+00],
       [  1.98500000e+03,              nan,              nan,
                     nan,   3.10000000e-01]])

In [11]:
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",", dtype="U75", skip_header=1)
print(world_alcohol)

[[u'1986' u'Western Pacific' u'Viet Nam' u'Wine' u'0']
 [u'1986' u'Americas' u'Uruguay' u'Other' u'0.5']
 [u'1985' u'Africa' u"Cte d'Ivoire" u'Wine' u'1.62']
 ..., 
 [u'1987' u'Africa' u'Malawi' u'Other' u'0.75']
 [u'1989' u'Americas' u'Bahamas' u'Wine' u'1.5']
 [u'1985' u'Africa' u'Malawi' u'Spirits' u'0.31']]


In [12]:
uruguay_other_1986 = world_alcohol[1,4]
third_country = world_alcohol[2,2]
print uruguay_other_1986
print third_country

0.5
Cte d'Ivoire


In [13]:
vector = numpy.array([5, 10, 15, 20])
print(vector[0:3])  

[ 5 10 15]


In [14]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,1])

[10 25 40]


In [15]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,0:2])

[[ 5 10]
 [20 25]
 [35 40]]


In [12]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[1:3,0:2])

[[20 25]
 [35 40]]
